# =============================================================================
# Apollo Deploy — Local Developer Variables
#
# All secrets are auto-generated by module "secrets". You don't need to set
# anything to get started. Optional service credentials can be added later.
# =============================================================================

# ── Service selection ─────────────────────────────────────────────────────────
variable "enable_signal" {
  description = "Deploy apollo-signal-api (requires CODEARTIFACT_AUTH_TOKEN env var to build)"
  type        = bool
  default     = true
}

variable "debug" {
  description = "Enable verbose dependency/build output for local Docker image builds"
  type        = bool
  default     = false
}

variable "dev_mode" {
  description = "Skip image builds; mount source trees and run bun --watch / gradlew run"
  type        = bool
  default     = false
}

# ── Migration control ─────────────────────────────────────────────────────────
variable "migration_trigger" {
  description = "Change to force re-run of migrations + OAuth registration (e.g. today's date)"
  type        = string
  default     = "initial"
}

# ── Polar (billing) ───────────────────────────────────────────────────────────
variable "polar_api_key" {
  description = "Polar.sh API key — required for billing subscription features"
  type        = string
  sensitive   = true
  default     = ""
}

variable "polar_webhook_secret" {
  description = "Polar.sh webhook signing secret"
  type        = string
  sensitive   = true
  default     = ""
}

# ── AWS (signal — SES, SQS) ───────────────────────────────────────────────────
variable "aws_access_key_id" {
  type      = string
  sensitive = true
  default   = ""
}

variable "aws_secret_access_key" {
  type      = string
  sensitive = true
  default   = ""
}

variable "aws_account_id" {
  type    = string
  default = ""
}

variable "sqs_webhook_queue_url" {
  type    = string
  default = ""
}

variable "sqs_scheduled_email_queue_url" {
  type    = string
  default = ""
}

variable "sqs_domain_verification_queue_url" {
  type    = string
  default = ""
}

# ── Template media (Cloudflare R2 / S3) ───────────────────────────────────────
variable "template_media_provider" {
  type    = string
  default = "r2"
}

variable "s3_template_media_bucket" {
  type    = string
  default = ""
}

variable "template_media_public_base_url" {
  type    = string
  default = ""
}

variable "r2_account_id" {
  type      = string
  sensitive = true
  default   = ""
}

variable "r2_access_key_id" {
  type      = string
  sensitive = true
  default   = ""
}

variable "r2_secret_access_key" {
  type      = string
  sensitive = true
  default   = ""
}

# ── Signal features ───────────────────────────────────────────────────────────
variable "signal_events_signing_secret" {
  description = "Webhook events signing secret — auto-generated by signal if blank"
  type        = string
  sensitive   = true
  default     = ""
}

variable "koog_api_key" {
  description = "koog-agents API key for AI features"
  type        = string
  sensitive   = true
  default     = ""
}

# ── SMS (signal) ──────────────────────────────────────────────────────────────
variable "telnyx_api_key" {
  type      = string
  sensitive = true
  default   = ""
}

variable "telnyx_messaging_profile_id" {
  type    = string
  default = ""
}
