# =============================================================================
# Apollo Deploy — Local Developer Variables
#
# All secrets are auto-generated by module "secrets". You don't need to set
# anything to get started. Optional service credentials can be added later.
# =============================================================================

# ── Service selection ─────────────────────────────────────────────────────────
variable "enable_signal" {
  description = "Deploy apollo-signal-api"
  type        = bool
  default     = true
}

variable "debug" {
  description = "Enable verbose dependency/build output for local Docker image builds"
  type        = bool
  default     = false
}

variable "dev_mode" {
  description = "Skip image builds; mount source trees. JVM services build a local app.jar, then run it directly."
  type        = bool
  default     = true
}

# ── Polar (billing) ───────────────────────────────────────────────────────────
variable "polar_api_key" {
  description = "Polar.sh API key — required for billing subscription features"
  type        = string
  sensitive   = true
  default     = ""
}

variable "polar_webhook_secret" {
  description = "Polar.sh webhook signing secret"
  type        = string
  sensitive   = true
  default     = ""
}

# ── AWS (signal — SES, SQS) ───────────────────────────────────────────────────
variable "aws_access_key_id" {
  description = "Optional AWS access key used by Signal for local SES and SQS integration"
  type        = string
  sensitive   = true
  default     = ""
}

variable "aws_secret_access_key" {
  description = "Optional AWS secret access key used by Signal for local SES and SQS integration"
  type        = string
  sensitive   = true
  default     = ""
}

variable "aws_account_id" {
  description = "Optional 12-digit AWS account ID used by Signal"
  type        = string
  default     = ""

  validation {
    condition     = var.aws_account_id == "" || can(regex("^[0-9]{12}$", var.aws_account_id))
    error_message = "aws_account_id must be empty or a 12-digit AWS account ID."
  }
}

variable "aws_region" {
  description = "Primary AWS region used by Signal during local development."
  type        = string
  default     = "af-south-1"

  validation {
    condition     = contains(["af-south-1", "ap-southeast-1", "eu-west-1", "us-east-1"], var.aws_region)
    error_message = "aws_region must be an Apollo-supported Signal region."
  }
}

variable "signal_supported_regions" {
  description = "AWS regions exposed by the local Signal runtime for sending domains and dedicated IPs."
  type        = set(string)
  default     = ["af-south-1", "ap-southeast-1", "eu-west-1"]

  validation {
    condition = (
      contains(var.signal_supported_regions, var.aws_region) &&
      alltrue([for region in var.signal_supported_regions : contains([
        "af-south-1",
        "ap-southeast-1",
        "eu-west-1",
        "us-east-1",
      ], region)])
    )
    error_message = "signal_supported_regions must include aws_region and contain only Apollo-supported regions."
  }
}

# ── Signal AWS S3 template media ──────────────────────────────────────────────
variable "s3_template_media_bucket" {
  description = "AWS S3 bucket used for Signal template media"
  type        = string
  default     = ""
}

variable "s3_project_archives_bucket" {
  description = "Private AWS S3 bucket used for Signal project deletion archives"
  type        = string
  default     = ""
}

variable "template_media_public_base_url" {
  description = "Optional public base URL for Signal template media"
  type        = string
  default     = ""

  validation {
    condition     = var.template_media_public_base_url == "" || can(regex("^https?://[^[:space:]]+$", var.template_media_public_base_url))
    error_message = "template_media_public_base_url must be empty or use http or https."
  }
}

# ── Signal features ───────────────────────────────────────────────────────────
variable "signal_events_signing_secret" {
  description = "Webhook events signing secret — auto-generated by signal if blank"
  type        = string
  sensitive   = true
  default     = ""
}

variable "koog_api_key" {
  description = "DeepSeek API key for AI features"
  type        = string
  sensitive   = true
  default     = ""
}
